window.PARTNERS = [
  {
    slug: 'bupa',
    name: 'Bupa',
    logo: 'assets/partners/bupa.webp',
    prizes: [
      {
        catalogId: 'bupa-gift-pack',
        catalogSponsor: 'Bupa',
        name: 'Bupa 大礼包',
        quantity: 3,
        image: 'assets/prizes/bupa-gift-pack.webp',
      },
    ],
    onsiteGift: {
      quantityLabel: '500+ 份',
      name: 'Bupa 新生健康福利包',
      items: ['健康纸巾', '品牌圆珠笔', '保湿唇膏'],
      evidencePattern: '500+ Bupa 新生健康福利包',
    },
  },
  {
    slug: 'fantuan',
    name: '饭团外卖',
    logo: 'assets/partners/fantuan.webp',
    onsiteGift: {
      quantityLabel: '1000+',
      name: '饭团外卖新人专属礼品',
      items: ['饭团玩偶', '手提袋', '饭团夹子', '留子手册'],
      evidencePattern: '1000+ 饭团外卖新人专属礼品',
    },
  },
  {
    slug: 'promosphone',
    name: 'PromosPhone',
    logo: 'assets/partners/promosphone.webp',
    prizes: [
      {
        catalogId: 'iwatch-se',
        catalogSponsor: 'PromosPhone',
        name: 'iWatch SE',
        quantity: 1,
        image: 'assets/prizes/promosphone-iwatch.webp',
      },
      {
        catalogId: 'airpods-4',
        catalogSponsor: 'PromosPhone',
        name: 'AirPods 4',
        quantity: 1,
      },
    ],
    onsiteGift: {
      quantityLabel: '400+',
      name: 'Promosphone 礼品',
      items: ['Promosphone定制香片'],
      evidencePattern: '400+Promosphone礼品',
    },
  },
  {
    slug: 'taoism-association',
    name: '澳大利亚中华道教协会',
    logo: 'assets/partners/taoism-association.webp',
    onsiteGift: {
      quantityLabel: '800+',
      name: '中华道教协会新生专属礼品',
      items: ['正能量挂件'],
      evidencePattern: '800+中华道教协会新生专属礼品',
    },
  },
  {
    slug: 'zircle',
    name: 'Zircle',
    logo: 'assets/partners/zircle.webp',
    onsiteGift: {
      quantityLabel: '100+',
      name: 'Zircle 新生礼包',
      items: ['Zircle手机支架', 'Zircle迷你钥匙扣', 'Zircle限定保温杯'],
      evidencePattern: '100+Zircle新生礼包',
    },
  },
  {
    slug: 'occom',
    name: 'Occom 澳世网络',
    logo: 'assets/partners/occom.webp',
    prizes: [
      {
        catalogId: 'tuf-be6500-router',
        catalogSponsor: 'ASUS',
        name: 'TUF-BE6500 路由器',
        quantity: 1,
        image: 'assets/prizes/occom-router.webp',
      },
    ],
    onsiteGift: {
      quantityLabel: '800+',
      name: 'Occom × ASUS 新生盲盒礼包',
      items: ['ASUS ROG 橄榄球', 'ASUS车载香薰', 'ASUS ROG 棒球帽', '城市限定冰箱贴', 'Occom IP笔记本'],
      evidencePattern: '800+OccomXASUS新生盲盒礼包',
    },
  },
  {
    slug: 'master-david',
    name: 'Master David 麻辣烫',
    logo: 'assets/partners/master-david.webp',
    onsiteGift: {
      quantityLabel: '400+',
      name: '大味麻辣烫美食福利',
      items: ['饮品', '零食', '惊喜周边若干'],
      evidencePattern: '400+ 大味麻辣烫美食福利',
    },
  },
  {
    slug: 'auspacific',
    name: '澳洲太平洋地产投资集团',
    logo: 'assets/partners/auspacific.webp',
    onsiteGift: {
      quantityLabel: '800+',
      name: '澳洲太平洋房地产新生专属好礼',
      items: ['新生入学及入住礼包'],
      evidencePattern: '800+ 澳洲太平洋房地产新生专属好礼',
    },
  },
  {
    slug: 'global-ballooning',
    name: '澳大利亚环球热气球',
    logo: 'assets/partners/global-ballooning.webp',
    prizes: [
      {
        catalogId: 'yarra-valley-flight',
        catalogSponsor: '澳环热气球',
        name: '亚拉河谷平日飞行券',
        quantity: 1,
        image: 'assets/prizes/global-ballooning-flight.webp',
      },
    ],
    onsiteGift: {
      quantityLabel: '800+',
      name: '新生热气球限定小礼物',
      items: ['限定明信片', '热气球徽章', '专属热气球帽子', 'Global潮流太阳眼镜'],
      evidencePattern: '800+澳大利亚环球热气球新生热气球限定小礼物',
    },
  },
  { slug: 'acic', name: 'ACIC 移民留学', logo: 'assets/partners/acic.webp' },
  {
    slug: 'dsoul',
    name: 'Dsoul 舞蹈工作室',
    logo: 'assets/partners/dsoul.webp',
    onsiteGift: {
      quantityLabel: '200+',
      name: 'Dsoul 舞蹈工作室首次免费体验卡',
      items: [],
      evidencePattern: '200+ Dsoul舞蹈工作室首次免费体验卡',
    },
  },
  {
    slug: 'dealmoon',
    name: 'DealMoon 澳洲省钱快报',
    logo: 'assets/partners/dealmoon.webp',
    prizes: [
      {
        catalogId: 'flexispot-chair',
        catalogSponsor: '澳洲省钱快报',
        name: 'FlexiSpot 人体工学椅',
        quantity: 1,
        image: 'assets/prizes/dealmoon-chair.webp',
      },
      { catalogId: 'keyboard-tray', catalogSponsor: '澳洲省钱快报', name: '键盘托', quantity: 1 },
      { catalogId: 'office-footrest', catalogSponsor: '澳洲省钱快报', name: '办公学习脚垫', quantity: 1 },
    ],
    onsiteGift: {
      quantityLabel: '800+',
      name: 'DealMoon 澳新新生专属礼包',
      items: ['墨尔本城市限定透卡（2款）', '可爱擦手巾', '小月亮帆布收纳包', 'tote包', '小零食'],
      evidencePattern: '800+ DealMoon澳新新生专属礼包',
    },
  },
  {
    slug: 'iceu',
    name: 'ICE U',
    logo: 'assets/partners/iceu.webp',
    prizes: [
      {
        catalogId: 'ice-u-dogs-session',
        catalogSponsor: 'ICE U',
        name: '双狗两小时使用权',
        quantity: 1,
        image: 'assets/prizes/iceu-dogs.webp',
      },
    ],
    onsiteGift: {
      quantityLabel: '800+',
      name: 'ICE U 新生礼包',
      items: ['十二生肖长脖子毛绒玩偶', '可爱卡通珊瑚绒挂巾', '筷子勺子叉子三件套', '定制扇子'],
      evidencePattern: '800+ICE U新生礼包',
    },
  },
  {
    slug: 'molly-tea',
    name: '茉莉奶白',
    logo: 'assets/partners/molly-tea.jpg',
    onsiteGift: {
      quantityLabel: '200 杯',
      name: '茉莉奶白花香茶饮福利',
      items: ['茉莉奶白 100 杯', '白兰金萱 100 杯'],
      evidencePattern: '200 杯茉莉奶白花香茶饮福利',
    },
  },
  { slug: 'jobpin-ai', name: 'JobPin AI', logo: 'assets/partners/jobpin-ai.webp' },
  {
    slug: 'haidilao',
    name: '海底捞',
    logo: 'assets/partners/haidilao.webp',
    prizes: [
      {
        catalogId: 'haidilao-plush-bag',
        catalogSponsor: '海底捞',
        name: '小捞捞毛绒包',
        quantity: 5,
        image: 'assets/prizes/haidilao-plush.webp',
      },
      { catalogId: 'haidilao-fruit-tea-cup', catalogSponsor: '海底捞', name: '果茶太空杯', quantity: 5 },
      { catalogId: 'haidilao-hotpot-blanket-pillow', catalogSponsor: '海底捞', name: '火锅锅底毛毯抱枕', quantity: 1 },
      { catalogId: 'haidilao-avocado-pillow', catalogSponsor: '海底捞', name: '牛油果抱枕', quantity: 1 },
    ],
    onsiteGift: {
      quantityLabel: '400+',
      name: '海底捞新生礼包',
      items: ['零食礼包'],
      evidencePattern: '400+海底捞新生礼包',
    },
  },
  {
    slug: 'wankawan',
    name: '玩咖玩乐馆',
    logo: 'assets/partners/wankawan.webp',
    onsiteGift: {
      quantityLabel: '300+',
      name: '玩咖玩乐馆新生礼包',
      items: ['熊猫冰箱贴', '传统文化节Ins框', '玩咖玩乐馆代金券', '古风市集通票门票', '古风市集第二场门票'],
      evidencePattern: '300+玩咖玩乐馆新生礼包',
    },
  },
  { slug: 'yeeyi', name: '亿忆网', logo: 'assets/partners/yeeyi.webp' },
  { slug: 'seventeen-club', name: '17 社', logo: 'assets/partners/seventeen-club.jpg' },
  {
    slug: 'umvc',
    name: '墨尔本创投社',
    logo: 'assets/partners/umvc.webp',
    onsiteGift: {
      quantityLabel: '100+',
      name: '墨尔本大学创投俱乐部校园礼包',
      items: ['墨大小熊', '水杯', '周边'],
      evidencePattern: '100+ 墨尔本大学创投俱乐部校园礼包',
    },
  },
  {
    slug: 'unimelb-cssa',
    name: '墨大 CSSA',
    logo: 'assets/partners/unimelb-cssa.webp',
    prizes: [
      {
        catalogId: 'unimelb-official-hoodie',
        catalogSponsor: '墨大 CSSA',
        name: 'UniMelb 官方卫衣',
        quantity: 2,
        image: 'assets/prizes/unimelb-hoodie.webp',
      },
      { catalogId: 'unimelb-blue-hoodie', catalogSponsor: '墨大 CSSA', name: 'UniMelb 深蓝色卫衣', quantity: 1 },
      { catalogId: 'unimelb-white-hoodie', catalogSponsor: '墨大 CSSA', name: 'UniMelb 白色卫衣', quantity: 1 },
      { catalogId: 'unimelb-graduation-bear-22cm', catalogSponsor: '墨大 CSSA', name: 'UniMelb 毕业小熊 22cm', quantity: 1 },
      { catalogId: 'unimelb-graduation-bear', catalogSponsor: '墨大 CSSA', name: 'UniMelb 毕业小熊', quantity: 1 },
    ],
    onsiteGift: {
      quantityLabel: '200+',
      name: 'UniMelb CSSA 学生会新生礼包',
      items: ['CSSA 专属 Showbag', 'CSSA 笔记本', 'CSSA 纪念笔', '零食若干', '饮品若干'],
      evidencePattern: '200+ UniMelb CSSA学生会新生礼包',
    },
  },
  {
    slug: 'monash-mcsa',
    name: 'Monash MCSA',
    logo: 'assets/partners/monash-mcsa.webp',
    onsiteGift: {
      quantityLabel: '100+',
      name: '蒙纳士中国学生会 MCSA 新生礼包',
      items: ['定制钥匙链', 'Logo 周边', '冰箱贴', '零食礼包'],
      evidencePattern: '100+ 蒙纳士中国学生会 MCSA 新生礼包',
    },
  },
];
